CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), email VARCHAR(255) UNIQUE NOT NULL, password VARCHAR(255) NOT NULL, full_name VARCHAR(255) NOT NULL, role VARCHAR(50) DEFAULT 'user', phone VARCHAR(50), department VARCHAR(255), bio TEXT, avatar_url TEXT, notification_preferences JSONB DEFAULT '{"email_reminders": true, "booking_confirmations": true, "weekly_digest": true}'::jsonb, theme_preference VARCHAR(20) DEFAULT 'light', created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE events ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), title VARCHAR(255) NOT NULL, description TEXT, category VARCHAR(50) NOT NULL, date DATE NOT NULL, start_time VARCHAR(5) NOT NULL, end_time VARCHAR(5) NOT NULL, location VARCHAR(255), capacity INTEGER NOT NULL, registered_count INTEGER DEFAULT 0, image_url TEXT, status VARCHAR(50) DEFAULT 'upcoming', is_recurring BOOLEAN DEFAULT false, recurrence_pattern VARCHAR(50), recurrence_end_date DATE, series_id VARCHAR(255), assigned_resource_ids TEXT[] DEFAULT ARRAY[]::TEXT[], created_by UUID REFERENCES users(id) ON DELETE SET NULL, created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE resources ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), name VARCHAR(255) NOT NULL, type VARCHAR(50) NOT NULL, description TEXT, capacity INTEGER, location VARCHAR(255), image_url TEXT, features TEXT[] DEFAULT ARRAY[]::TEXT[], available BOOLEAN DEFAULT true, created_by UUID REFERENCES users(id) ON DELETE SET NULL, created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE bookings ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), booking_type VARCHAR(50) NOT NULL, event_id UUID REFERENCES events(id) ON DELETE CASCADE, resource_id UUID REFERENCES resources(id) ON DELETE CASCADE, date DATE NOT NULL, start_time VARCHAR(5) NOT NULL, end_time VARCHAR(5) NOT NULL, purpose TEXT, status VARCHAR(50) DEFAULT 'confirmed', notes TEXT, created_by UUID REFERENCES users(id) ON DELETE CASCADE, created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE ratings ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), rating_type VARCHAR(50) NOT NULL, event_id UUID REFERENCES events(id) ON DELETE CASCADE, resource_id UUID REFERENCES resources(id) ON DELETE CASCADE, rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5), review TEXT, created_by UUID REFERENCES users(id) ON DELETE CASCADE, created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP );

CREATE TABLE waiting_list ( id UUID PRIMARY KEY DEFAULT uuid_generate_v4(), event_id UUID REFERENCES events(id) ON DELETE CASCADE, user_id UUID REFERENCES users(id) ON DELETE CASCADE, user_email VARCHAR(255) NOT NULL, position INTEGER NOT NULL, status VARCHAR(50) DEFAULT 'waiting', notified_date TIMESTAMP, created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP, UNIQUE(event_id, user_id) );

CREATE INDEX idx_events_date ON events(date); CREATE INDEX idx_events_category ON events(category); CREATE INDEX idx_events_status ON events(status); CREATE INDEX idx_bookings_date ON bookings(date); CREATE INDEX idx_bookings_user ON bookings(created_by); CREATE INDEX idx_ratings_event ON ratings(event_id); CREATE INDEX idx_ratings_resource ON ratings(resource_id); CREATE INDEX idx_waitinglist_event ON waiting_list(event_id);